sudo: true
dist: xenial

before_install:
#  Install newest docker
    - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
    - sudo apt-get update
    - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
#  Get Image with ROOT + LHAPDF
    - docker pull zleba/rootlhapdf:system

script:
#Get and compile dependences
    - export PROJECT_DIR=$PWD
    - export PATH=$PWD:$PATH
    - rd ./installQCDnum.sh
    - rd ./installFast.sh
    - rd ./installApfelxx.sh
    - rd ./installPlHelper.sh
#Compile Alpos
    - rd ./installAlpos.sh
#Run test
    - cd alpos/farm/
    - ln -s $PROJECT_DIR/alpos/datafiles
    - rd ./run.py -t -r testPdfNLO
    - cd $PROJECT_DIR/alpos/macros
    - rd root -l -b -q dplotterErr.C

      #    - ln -s alpos/datafiles
      #    - ./rd  alposBuild/alpos alpos/steering/H1diff.str
      #    - ./rd root -l -b -q alpos/macros/dplotter.C


deploy:
    provider: pages
    local-dir : alpos/farm/testPdfNLO/dPlots
    skip-cleanup: true
    github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
    keep-history: false
    on:
        branch: master
