sudo: true
dist: xenial

before_install:
#  Install newest docker
    - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
    - sudo apt-get update
    - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
#  Get Image with ROOT + LHAPDF
    - docker pull zleba/rootlhapdf:system

script:
#Get and compile dependences
    - ./rd ./installQCDnum.sh
    - ./rd ./installFast.sh
    - ./rd ./installApfelxx.sh
    - ./rd ./installPlHelper.sh
#Compile Alpos
    - ./rd ./installAlpos.sh
#Run test
    - ln -s alpos/datafiles
    - ./rd  alposBuild/alpos alpos/steering/H1diff.str
    - cp test/alpos.out.root  alpos/test/alpos.out.root
    - cd alpos/macros/
    - ./rd root -l -b -q dplotter.C


deploy:
    provider: pages
    local-dir : alpos/macros/dPlots
    skip-cleanup: true
    github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
    keep-history: false
    on:
        branch: master
