sudo: true
dist: xenial

before_install:
#    - Get Image with ROOT + LHAPDF
    - docker pull zleba/rootlhapdf:system

script:
#Get and compile dependences
    - ./rd ./installQCDnum.sh
    - ./rd ./installFast.sh
#Compile Alpos
    - ./rd ./installAlpos.sh
#Run test
    - cd alpos
    - ./rd  ../alposBuild/alpos steering/H1diff.str
        
